// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdVveBMuJevsN6_XoXhZx6YmTDn-rBj5Y',
    appId: '1:62540229880:web:dcd8a6c9dee72ac52ddf0d',
    messagingSenderId: '62540229880',
    projectId: 'nurcanfirstapp',
    authDomain: 'nurcanfirstapp.firebaseapp.com',
    storageBucket: 'nurcanfirstapp.appspot.com',
    measurementId: 'G-G85Z1F0D2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFx_k79HPSyubTkwdxNSPfFurgdiV4zqM',
    appId: '1:62540229880:android:90ffbb28dc1100ac2ddf0d',
    messagingSenderId: '62540229880',
    projectId: 'nurcanfirstapp',
    storageBucket: 'nurcanfirstapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz39dMmjM8blUO4-SBMHohHzA9E8Q3fTU',
    appId: '1:62540229880:ios:da700e1748af85a02ddf0d',
    messagingSenderId: '62540229880',
    projectId: 'nurcanfirstapp',
    storageBucket: 'nurcanfirstapp.appspot.com',
    iosBundleId: 'com.example.firstflut',
  );
}
